### ISSUE TITLE
When using the default profile picture like I do, it's too big

### ISSUE THREAD

**Issue by joshuajohncohen** [openscript/openscript#4]
Screenshot:
![image](https://github.com/openscript/openscript/assets/65085812/5c2db202-148e-4ddc-b4c6-f3f591dd9609)

Github returns a 420x420 image regardless of the ?s=24 parameter for default profile pictures.

**Comment by openscript** [comment]
Thanks for raising this issue. I've fixed it. Cheers :beers:
